[package]
name = "neural"
description = "Genetic Algorithms in Rust"
version = "0.4.0"
authors = ["DarkCeptor44"]
edition = "2024"
rust-version = "1.85"
license = "MIT"
keywords = ["neural-network", "genetic-algorithm"]
categories = ["algorithms"]
repository = "https://github.com/DarkCeptor44/neural"
homepage = "https://docs.rs/neural"

[features]
default = []
print = ["dep:colored"]

[dependencies]
rand = "0.10.1"
thiserror = "2.0.18"

colored = { version = "3.1.1", optional = true }

[package.metadata.docs.rs]
all-features = true

[package.metadata.playground]
all-features = true
